// Notification Types - unified across all files
export const NOTIFICATION_TYPES = {
  SUCCESS: "success",
  WELCOME: "WELCOME",
  EMI_REMINDER: "EMI_REMINDER",
  RATE_UPDATE: "RATE_UPDATE",
  SECURITY_ALERT: "SECURITY_ALERT",
  LOGIN_ALERT: "LOGIN_ALERT",
  INFO: "info",
  WARNING: "warning",
  ALERT: "alert",
};

// UI Types - how notifications appear in frontend
export const UI_TYPES = {
  SUCCESS: "success",
  INFO: "info",
  WARNING: "warning",
  ALERT: "alert",
  ERROR: "error",
};

// Categories - for filtering notifications
export const NOTIFICATION_CATEGORIES = {
  LOAN: "loan",
  SCHEME: "scheme",
  PAYMENT: "payment",
  DOCUMENT: "document",
  SECURITY: "security",
  MESSAGE: "message",
  ACCOUNT: "account",
  RATE: "rate",
  OTHER: "other",
};

// Notification Priority
export const PRIORITY_LEVELS = {
  LOW: "low",
  MEDIUM: "medium",
  HIGH: "high",
};

// Delivery Methods
export const DELIVERY_METHODS = {
  EMAIL: "EMAIL",
  SMS: "SMS",
  PUSH: "PUSH_NOTIFICATION",
  IN_APP: "IN_APP",
};

// Type to UI Type Mapping
export const TYPE_TO_UI_TYPE = {
  [NOTIFICATION_TYPES.SUCCESS]: UI_TYPES.SUCCESS,
  [NOTIFICATION_TYPES.WELCOME]: UI_TYPES.SUCCESS,
  [NOTIFICATION_TYPES.EMI_REMINDER]: UI_TYPES.WARNING,
  [NOTIFICATION_TYPES.RATE_UPDATE]: UI_TYPES.INFO,
  [NOTIFICATION_TYPES.SECURITY_ALERT]: UI_TYPES.ALERT,
  [NOTIFICATION_TYPES.LOGIN_ALERT]: UI_TYPES.ALERT,
  [NOTIFICATION_TYPES.INFO]: UI_TYPES.INFO,
  [NOTIFICATION_TYPES.WARNING]: UI_TYPES.WARNING,
  [NOTIFICATION_TYPES.ALERT]: UI_TYPES.ALERT,
};

// Type to Category Mapping
export const TYPE_TO_CATEGORY = {
  [NOTIFICATION_TYPES.SUCCESS]: NOTIFICATION_CATEGORIES.LOAN,
  [NOTIFICATION_TYPES.WELCOME]: NOTIFICATION_CATEGORIES.ACCOUNT,
  [NOTIFICATION_TYPES.EMI_REMINDER]: NOTIFICATION_CATEGORIES.PAYMENT,
  [NOTIFICATION_TYPES.RATE_UPDATE]: NOTIFICATION_CATEGORIES.RATE,
  [NOTIFICATION_TYPES.SECURITY_ALERT]: NOTIFICATION_CATEGORIES.SECURITY,
  [NOTIFICATION_TYPES.LOGIN_ALERT]: NOTIFICATION_CATEGORIES.SECURITY,
};
